### ISSUE TITLE
Create script to read multiple domain data

### ISSUE THREAD

**Issue by njallskarp** [njallskarp/finetune-qa-powerset#17]
# Read Data

Currently, the data is stored on Labelstudio. We need to fetch the data. We already have a starter code, but we need to make it A) prettier and B) make sure that all passwords, tokens, etc are environment variables and not commited in code

**Comment by lsig** [comment]
This issue should be done see #51, where I have written a script to fetch the data from labeling studio with the requirements above in mind.
